### PR TITLE
Change add and set to take and return &mut self

### LINKED ISSUE #22: Take &mut self instead of self in builders
See https://rust-lang-nursery.github.io/api-guidelines/type-safety.html#builders-enable-construction-of-complex-values-c-builder

### PR DESCRIPTION
**Pull request by IvanUkhov**
Closes #22.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
The problem is that the example given in the documentation does not work with these changes.

```rust
let path = Path::new() // path is now &mut Node, not Node
    .set("fill", "none")
    .set("stroke", "black")
    .set("stroke-width", 3)
    .set("d", data);

let document = Document::new()
    .set("viewBox", (0, 0, 70, 70))
    .add(path); // can only take Node, not &mut Node
```

It would be nice to keep examples and all code working as before.

Any suggestions?

**Comment by MichaelMauderer** [comment]
I don't think that is possible to modify the signature and keep the current behavior.

For backwards compatibility, it might be easier to add new functions that don't consume `self`.
For example `set_mut`, `add_mut` etc.

**Comment by IvanUkhov** [comment]
I mean the signature should change to accommodate passing by both value and reference.

**Comment by MichaelMauderer** [comment]
That is what I mean. I don't think that can be safely done.
It might be worth asking in the [rust user forum](https://users.rust-lang.org/) though.

**Comment by IvanUkhov** [comment]
I don’t do Rust on a daily basis these days, and my knowledge might be a bit rusty, but I believe there is a way to make it work, using `AsRef` and friends or a custom trait with a similar behavior. I’ll give it a try, but I think it’s a good idea about the user forum.

**Comment by IvanUkhov** [comment]
The last commit shows how it could be done by changing `append` instead. However,

```
error[E0716]: temporary value dropped while borrowed
  --> src/lib.rs:19:12
   |
15 | let path = Path::new()
   |            ^^^^^^^^^^^ creates a temporary which is freed while still in use
...
19 |     .set("d", data);
   |                    - temporary value is freed at the end of this statement
...
23 |     .add(path);
   |          ---- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value

error[E0716]: temporary value dropped while borrowed
  --> src/lib.rs:25:16
   |
21 | let document = Document::new()
   |                ^^^^^^^^^^^^^^^ creates a temporary which is freed while still in use
22 |     .set("viewBox", (0, 0, 70, 70))
23 |     .add(path);
   |               - temporary value is freed at the end of this statement
24 |
25 | svg::save("image.svg", document).unwrap();
   |                        -------- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value
```

In other words, since the builder never actually builds, it gets freed right after the last statement.

**Comment by IvanUkhov** [comment]
For now, it’s not clear if this would add value.

**Pull request closed without merging**
