### PR TITLE
Add HTML Link, used for stylesheets

### PR DESCRIPTION
**Pull request by jgreenbaum**
There didn't seem to be a way to add a <link> tag for stylesheets. Here I add the HtmlLink type (see https://www.w3.org/TR/SVG/styling.html#LinkElement). The typical usage looks like this:
```
svg_doc = svg_doc.add(HtmlLink::new()
        .set("xmlns", "http://www.w3.org/1999/xhtml")
        .set("rel","stylesheet")
        .set("type","text/css")
        .set("href", "my_stylesheet_url"));
```

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Hm, good point. Thank you. I am at an impasse now. `HtmlLink` does not feel right. It is very tempting to rename `Link` to `Anchor` and `HtmlLink` to `Link`. It can potentially screw up things for a lot of people, but provided there would be a version bump, it seems to be the right thing to do. What do you think? Would you be able to update the PR?

**Comment by jgreenbaum** [comment]
I'm exactly of the same mind as you ... it is unfortunate that tag 'a' is named Link, but  I worry about breaking the world to change it when it seems there are many users. I chose HtmlLink since that is how the SVG spec describes it and doesn't require an API change.

I'm happy to update the PR at any time.

I'd hate to suggest that adding the <link> tag is so groundbreaking as to inspire a new major version, but that might be the right thing to do if it requires an API breaking change. Are you ready to otherwise call it 1.0? Are there other changes in the queue that would be breaking as well?

**Comment by IvanUkhov** [comment]
Not sure if I am ready to call it 1.0. I will increment the minor version for now. So let us break it! 😀

**Comment by jgreenbaum** [comment]
I appreciate your enthusiasm! I'll update the PR ...

**Comment by jgreenbaum** [comment]
I've updated the pull request, and tested lightly with my application.

**Comment by IvanUkhov** [comment]
Thank you!

**Pull request merged**
